### ISSUE TITLE
You have an error in your SQL syntax

### ISSUE THREAD

**Issue by wp-newbiefriendly** [dpdconnect/woocommerce-shipping#31]
Hello,

We're optimizing our site, and using plugin Query Monitor.. It's slowing our admin dashboard too much. There is some dpd error in query database tab: 

Error Message
You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'IF' at line 1

Caller:
DpdConnect\c\H\Activate::updateDb()
wp-content/plugins/dpdconnect/classes/Handlers/Activate.php:35
DpdConnect\c\H\Activate::handle()
wp-content/plugins/dpdconnect/classes/Handlers/Activate.php:10

**Comment by dpdplugin** [comment]
Hi @wp-newbiefriendly ,

What database and what plugin version are you using exactly?

**Comment by wp-newbiefriendly** [comment]
Hello, thanks for answering.
I use 1.3.2 latest plugin version and MySQL on server Plesk Obsidian v18.0.41 - Ubuntu 20.04.4 LTS

**Comment by wp-newbiefriendly** [comment]
Anyone some ideas?

**Comment by D0nVit0** [comment]
They released a new version 8 hours ago. It might be worth a try, perhaps it will solve your issue.
https://github.com/dpdconnect/woocommerce-shipping/releases/tag/1.3.3

**Comment by wp-newbiefriendly** [comment]
Thanks, I updated plugin, but problem stays same.

**Comment by dpdplugin** [comment]
It seems to be a problem with the database version, we are still looking further into it.

**Comment by wp-newbiefriendly** [comment]
If you find solution would you tell us here?

**Comment by codeyy** [comment]
We're having the same issue with PHP 7.4 and MySQL 5.7.37.

**Comment by dpdplugin** [comment]
This has been fixed in release 1.3.4, it was an issue in `dbDelta()`.
The function interpeted IF as an table, its a known issue in the Wordpress core.

**Comment by sanderjn** [comment]
I'm still experiencing major issues with 1.3.4 as well. Admin becomes practically unusable after filling in Login Details (50+s page load). Works fine when deleting Login Details.

Using query monitor I can see some PHP errors:
- Undefined array key "token"
- Undefined array key 0
- Undefined array key 1
