### ISSUE TITLE
Webshop extremely slow

### ISSUE THREAD

**Issue by OlrikNijmeijer** [dpdconnect/woocommerce-shipping#46]
Hello,

We have installed the latest version of the plugin in a WooCommerce webshop with 4000+ products.
When we add something to the cart it takes a few minutes to do this.

Also adding/editing the shipping methods in the backend is very slow.(pages take a few minutes to load)

When we disabled the plugin, adding a product to the cart is almost instant. Same goes for adding/editing shipping methods in the backend.

We used a debug plugin to try to find slow functions and the function "addCustomSettings" is executed around 30 times, taking at least 6 seconds every execution.

Can you help us identify the problem?

**Comment by dpdplugin** [comment]
Hi @OlrikNijmeijer ,

This should be fixed in the latest release (1.4.0).
There was an issue with the cache not being able to save on specific server configurations or on Windows servers especially.

**Comment by OlrikNijmeijer** [comment]
@dpdplugin Unfortunately the update did not fix the issue. We even tried to put the webshop on a different server, but on both servers the issue is still there.

Do you need more information from us? Or do you want to debug on a development site we have?
